### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by st1553** [egol/RustCal#1]
This is really cool looking and something thats needed because most rust calendar offerings want to plug into google calendar or similar. This is standalone and simple and I need something like this. But because it uses these backend libraries that I know get modified periodically and thus need updates to the code that uses it, I don't want to use something that's dead and hence will become my problem to maintain henceforth.

**Comment by st1553** [comment]
The code thats up now doesnt work like the picture shows ie you cant actually schedule an event. In fact the Enter key functionality is commented out completely:
let offsets = match event {
            Event::Key(Key::Up) => Some((0, -1, 0, 0)
            ),
            Event::Key(Key::Down) => Some((0, 1, 0, 0)
            ),
            Event::Key(Key::Right) => Some((1, 0, 0, 0)
            ),
            Event::Key(Key::Left) => Some((-1, 0, 0, 0)
            ),
            // Event::Key(Key::PageUp) => Some((0, 0, 1, 0)
            // ),
            // Event::Key(Key::PageDown) => Some((0, 0, -1, 0)
            // ),
            // Event::Mouse(Mouse::offset) => Some((0, -1, 0),
            //Event::Key(Key::Backspace) => {}
            // Event::Key(Key::Enter) => {}
            _ => None,
        };

**Comment by egol** [comment]
Yeah this project has been dead for a quite a while now, thank you for the sudden and unexpected interest.
In terms of the libraries the only vital one is Cursive as it creates the terminal based ui (i.e. the entire project). As it needs to communicate with platform specific terminals, it needs semi-frequent updates to keep working. As some terminals do eventually receive updates to their functionality, i.e. windows 11.
As for the enter key, to create an event I currently have it set to right mouse button.
Out of an abundance of time I will try to do some refactoring and update this project to the latest Cursive version (as well as make the binding make more sense).
